settings:
  title: 'Re_Project_Services'
  url: 'https://status.r6s.wtf' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: ETalk Website # unique identifier
    name: ETalk Website
    description: 'ETalk WebSite Status' # default=empty
    url: 'https://talk.r6s.wtf' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: KnLive
    name: KnLive Site.
    description: 'KnLive'
    url: 'https://emolive.eu.org'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
  
  - id: Live Stream
    name: Hong-Kong Live Stream Server
    description: 'ETalk Services[BETA]'
    url: 'https://1live.emolive.eu.org'
    method: GET
    expectStatus: 200
    linkable: false